// Code generated by protoc-gen-go-grpc. DO NOT EDIT.
// versions:
// - protoc-gen-go-grpc v1.6.1
// - protoc             v7.34.1
// source: proto/brain.proto

package proto

import (
	context "context"
	grpc "google.golang.org/grpc"
	codes "google.golang.org/grpc/codes"
	status "google.golang.org/grpc/status"
)

// This is a compile-time assertion to ensure that this generated file
// is compatible with the grpc package it is being compiled against.
// Requires gRPC-Go v1.64.0 or later.
const _ = grpc.SupportPackageIsVersion9

const (
	BrainService_ProcessDocument_FullMethodName = "/brain.BrainService/ProcessDocument"
	BrainService_Chat_FullMethodName            = "/brain.BrainService/Chat"
)

// BrainServiceClient is the client API for BrainService service.
//
// For semantics around ctx use and closing/ending streaming RPCs, please refer to https://pkg.go.dev/google.golang.org/grpc/?tab=doc#ClientConn.NewStream.
type BrainServiceClient interface {
	// Go akan memanggil fungsi ini, mengirim dokumen, lalu Python membalas statusnya
	ProcessDocument(ctx context.Context, in *DocumentRequest, opts ...grpc.CallOption) (*DocumentResponse, error)
	Chat(ctx context.Context, in *ChatRequest, opts ...grpc.CallOption) (*ChatResponse, error)
}

type brainServiceClient struct {
	cc grpc.ClientConnInterface
}

func NewBrainServiceClient(cc grpc.ClientConnInterface) BrainServiceClient {
	return &brainServiceClient{cc}
}

func (c *brainServiceClient) ProcessDocument(ctx context.Context, in *DocumentRequest, opts ...grpc.CallOption) (*DocumentResponse, error) {
	cOpts := append([]grpc.CallOption{grpc.StaticMethod()}, opts...)
	out := new(DocumentResponse)
	err := c.cc.Invoke(ctx, BrainService_ProcessDocument_FullMethodName, in, out, cOpts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

func (c *brainServiceClient) Chat(ctx context.Context, in *ChatRequest, opts ...grpc.CallOption) (*ChatResponse, error) {
	cOpts := append([]grpc.CallOption{grpc.StaticMethod()}, opts...)
	out := new(ChatResponse)
	err := c.cc.Invoke(ctx, BrainService_Chat_FullMethodName, in, out, cOpts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

// BrainServiceServer is the server API for BrainService service.
// All implementations must embed UnimplementedBrainServiceServer
// for forward compatibility.
type BrainServiceServer interface {
	// Go akan memanggil fungsi ini, mengirim dokumen, lalu Python membalas statusnya
	ProcessDocument(context.Context, *DocumentRequest) (*DocumentResponse, error)
	Chat(context.Context, *ChatRequest) (*ChatResponse, error)
	mustEmbedUnimplementedBrainServiceServer()
}

// UnimplementedBrainServiceServer must be embedded to have
// forward compatible implementations.
//
// NOTE: this should be embedded by value instead of pointer to avoid a nil
// pointer dereference when methods are called.
type UnimplementedBrainServiceServer struct{}

func (UnimplementedBrainServiceServer) ProcessDocument(context.Context, *DocumentRequest) (*DocumentResponse, error) {
	return nil, status.Error(codes.Unimplemented, "method ProcessDocument not implemented")
}
func (UnimplementedBrainServiceServer) Chat(context.Context, *ChatRequest) (*ChatResponse, error) {
	return nil, status.Error(codes.Unimplemented, "method Chat not implemented")
}
func (UnimplementedBrainServiceServer) mustEmbedUnimplementedBrainServiceServer() {}
func (UnimplementedBrainServiceServer) testEmbeddedByValue()                      {}

// UnsafeBrainServiceServer may be embedded to opt out of forward compatibility for this service.
// Use of this interface is not recommended, as added methods to BrainServiceServer will
// result in compilation errors.
type UnsafeBrainServiceServer interface {
	mustEmbedUnimplementedBrainServiceServer()
}

func RegisterBrainServiceServer(s grpc.ServiceRegistrar, srv BrainServiceServer) {
	// If the following call panics, it indicates UnimplementedBrainServiceServer was
	// embedded by pointer and is nil.  This will cause panics if an
	// unimplemented method is ever invoked, so we test this at initialization
	// time to prevent it from happening at runtime later due to I/O.
	if t, ok := srv.(interface{ testEmbeddedByValue() }); ok {
		t.testEmbeddedByValue()
	}
	s.RegisterService(&BrainService_ServiceDesc, srv)
}

func _BrainService_ProcessDocument_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(DocumentRequest)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(BrainServiceServer).ProcessDocument(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: BrainService_ProcessDocument_FullMethodName,
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(BrainServiceServer).ProcessDocument(ctx, req.(*DocumentRequest))
	}
	return interceptor(ctx, in, info, handler)
}

func _BrainService_Chat_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(ChatRequest)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(BrainServiceServer).Chat(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: BrainService_Chat_FullMethodName,
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(BrainServiceServer).Chat(ctx, req.(*ChatRequest))
	}
	return interceptor(ctx, in, info, handler)
}

// BrainService_ServiceDesc is the grpc.ServiceDesc for BrainService service.
// It's only intended for direct use with grpc.RegisterService,
// and not to be introspected or modified (even as a copy)
var BrainService_ServiceDesc = grpc.ServiceDesc{
	ServiceName: "brain.BrainService",
	HandlerType: (*BrainServiceServer)(nil),
	Methods: []grpc.MethodDesc{
		{
			MethodName: "ProcessDocument",
			Handler:    _BrainService_ProcessDocument_Handler,
		},
		{
			MethodName: "Chat",
			Handler:    _BrainService_Chat_Handler,
		},
	},
	Streams:  []grpc.StreamDesc{},
	Metadata: "proto/brain.proto",
}
