// Versi protobuf yang kita gunakan

// Code generated by protoc-gen-go. DO NOT EDIT.
// versions:
// 	protoc-gen-go v1.36.11
// 	protoc        v7.34.1
// source: proto/brain.proto

// Nama paket/namespace kontrak ini

package proto

import (
	protoreflect "google.golang.org/protobuf/reflect/protoreflect"
	protoimpl "google.golang.org/protobuf/runtime/protoimpl"
	reflect "reflect"
	sync "sync"
	unsafe "unsafe"
)

const (
	// Verify that this generated code is sufficiently up-to-date.
	_ = protoimpl.EnforceVersion(20 - protoimpl.MinVersion)
	// Verify that runtime/protoimpl is sufficiently up-to-date.
	_ = protoimpl.EnforceVersion(protoimpl.MaxVersion - 20)
)

// Data yang dikirim dari Go ke Python
type DocumentRequest struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	FileName      string                 `protobuf:"bytes,1,opt,name=file_name,json=fileName,proto3" json:"file_name,omitempty"` // Angka 1, 2, 3 ini adalah "Tag" unik, bukan nilai default!
	Author        string                 `protobuf:"bytes,2,opt,name=author,proto3" json:"author,omitempty"`
	Content       []byte                 `protobuf:"bytes,3,opt,name=content,proto3" json:"content,omitempty"` // Nanti file fisik PDF-nya dikirim dalam bentuk bytes
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *DocumentRequest) Reset() {
	*x = DocumentRequest{}
	mi := &file_proto_brain_proto_msgTypes[0]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *DocumentRequest) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*DocumentRequest) ProtoMessage() {}

func (x *DocumentRequest) ProtoReflect() protoreflect.Message {
	mi := &file_proto_brain_proto_msgTypes[0]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use DocumentRequest.ProtoReflect.Descriptor instead.
func (*DocumentRequest) Descriptor() ([]byte, []int) {
	return file_proto_brain_proto_rawDescGZIP(), []int{0}
}

func (x *DocumentRequest) GetFileName() string {
	if x != nil {
		return x.FileName
	}
	return ""
}

func (x *DocumentRequest) GetAuthor() string {
	if x != nil {
		return x.Author
	}
	return ""
}

func (x *DocumentRequest) GetContent() []byte {
	if x != nil {
		return x.Content
	}
	return nil
}

// Data balasan dari Python ke Go
type DocumentResponse struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	Success       bool                   `protobuf:"varint,1,opt,name=success,proto3" json:"success,omitempty"`
	Message       string                 `protobuf:"bytes,2,opt,name=message,proto3" json:"message,omitempty"`
	DocumentId    string                 `protobuf:"bytes,3,opt,name=document_id,json=documentId,proto3" json:"document_id,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *DocumentResponse) Reset() {
	*x = DocumentResponse{}
	mi := &file_proto_brain_proto_msgTypes[1]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *DocumentResponse) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*DocumentResponse) ProtoMessage() {}

func (x *DocumentResponse) ProtoReflect() protoreflect.Message {
	mi := &file_proto_brain_proto_msgTypes[1]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use DocumentResponse.ProtoReflect.Descriptor instead.
func (*DocumentResponse) Descriptor() ([]byte, []int) {
	return file_proto_brain_proto_rawDescGZIP(), []int{1}
}

func (x *DocumentResponse) GetSuccess() bool {
	if x != nil {
		return x.Success
	}
	return false
}

func (x *DocumentResponse) GetMessage() string {
	if x != nil {
		return x.Message
	}
	return ""
}

func (x *DocumentResponse) GetDocumentId() string {
	if x != nil {
		return x.DocumentId
	}
	return ""
}

var File_proto_brain_proto protoreflect.FileDescriptor

const file_proto_brain_proto_rawDesc = "" +
	"\n" +
	"\x11proto/brain.proto\x12\x05brain\"`\n" +
	"\x0fDocumentRequest\x12\x1b\n" +
	"\tfile_name\x18\x01 \x01(\tR\bfileName\x12\x16\n" +
	"\x06author\x18\x02 \x01(\tR\x06author\x12\x18\n" +
	"\acontent\x18\x03 \x01(\fR\acontent\"g\n" +
	"\x10DocumentResponse\x12\x18\n" +
	"\asuccess\x18\x01 \x01(\bR\asuccess\x12\x18\n" +
	"\amessage\x18\x02 \x01(\tR\amessage\x12\x1f\n" +
	"\vdocument_id\x18\x03 \x01(\tR\n" +
	"documentId2R\n" +
	"\fBrainService\x12B\n" +
	"\x0fProcessDocument\x12\x16.brain.DocumentRequest\x1a\x17.brain.DocumentResponseB\tZ\a./protob\x06proto3"

var (
	file_proto_brain_proto_rawDescOnce sync.Once
	file_proto_brain_proto_rawDescData []byte
)

func file_proto_brain_proto_rawDescGZIP() []byte {
	file_proto_brain_proto_rawDescOnce.Do(func() {
		file_proto_brain_proto_rawDescData = protoimpl.X.CompressGZIP(unsafe.Slice(unsafe.StringData(file_proto_brain_proto_rawDesc), len(file_proto_brain_proto_rawDesc)))
	})
	return file_proto_brain_proto_rawDescData
}

var file_proto_brain_proto_msgTypes = make([]protoimpl.MessageInfo, 2)
var file_proto_brain_proto_goTypes = []any{
	(*DocumentRequest)(nil),  // 0: brain.DocumentRequest
	(*DocumentResponse)(nil), // 1: brain.DocumentResponse
}
var file_proto_brain_proto_depIdxs = []int32{
	0, // 0: brain.BrainService.ProcessDocument:input_type -> brain.DocumentRequest
	1, // 1: brain.BrainService.ProcessDocument:output_type -> brain.DocumentResponse
	1, // [1:2] is the sub-list for method output_type
	0, // [0:1] is the sub-list for method input_type
	0, // [0:0] is the sub-list for extension type_name
	0, // [0:0] is the sub-list for extension extendee
	0, // [0:0] is the sub-list for field type_name
}

func init() { file_proto_brain_proto_init() }
func file_proto_brain_proto_init() {
	if File_proto_brain_proto != nil {
		return
	}
	type x struct{}
	out := protoimpl.TypeBuilder{
		File: protoimpl.DescBuilder{
			GoPackagePath: reflect.TypeOf(x{}).PkgPath(),
			RawDescriptor: unsafe.Slice(unsafe.StringData(file_proto_brain_proto_rawDesc), len(file_proto_brain_proto_rawDesc)),
			NumEnums:      0,
			NumMessages:   2,
			NumExtensions: 0,
			NumServices:   1,
		},
		GoTypes:           file_proto_brain_proto_goTypes,
		DependencyIndexes: file_proto_brain_proto_depIdxs,
		MessageInfos:      file_proto_brain_proto_msgTypes,
	}.Build()
	File_proto_brain_proto = out.File
	file_proto_brain_proto_goTypes = nil
	file_proto_brain_proto_depIdxs = nil
}
